version: 1

environment:
  php: 8.3
  node: 20

services:
  - docker:

secrets:
  - GITHUB_TOKEN
  - GITHUB_USERNAME

pipeline:
  - name: Composer Install
    cmd: |
      composer install

  - name: NPM Install
    cmd: |
      npm install

#  - name: Ziggy Generate
#    cmd: |
#      php artisan ziggy:generate

  - name: NPM Build
    cmd: |
      npm run build

  - name: Docker Login
    cmd: |
      echo "$GITHUB_TOKEN" \
        | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin

  - name: Build and Push Docker Image
    cmd: |
      docker build \
        -t ghcr.io/andy3471/keyshare:latest \
        -f ./docker/production/Dockerfile .
      docker push ghcr.io/andy3471/keyshare:latest

  - name: Deploy to Server
    secrets:
      - DEPLOY_KEY
    cmd: |
      ssh -o StrictHostKeyChecking=no admin@andrewflix.uk "
        cd /home/admin/keyshare-demo &&
        docker compose pull &&
        docker compose up -d &&
        docker compose exec -T keyshare php artisan view:cache &&
        docker compose exec -T keyshare php artisan migrate --force &&
        docker compose exec -T keyshare php artisan cache:all
      "
