version: '3'
services:
  web:
    build: .
    restart: unless-stopped
    container_name: keyshare-web
    ports:
      - "3472:80"
    env_file:
      - .env
    environment:
      DB_HOST: db
      APP_ENV: local
      APP_DEBUG: "true"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7.30
    restart: unless-stopped
    container_name: keyshare-db
    ports:
     - "3306:3306"
    environment:
     MYSQL_DATABASE: ${DB_DATABASE}
     MYSQL_USER: ${DB_USERNAME}
     MYSQL_PASSWORD: ${DB_PASSWORD}
     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  redis:
    image: redis:6.0.4
    container_name: keyshare-redis
    restart: unless-stopped
    entrypoint: redis-server --appendonly yes