version: '3'
services:
   lunchrota-web:
    image: andy3471/lunchrota
    restart: unless-stopped
    ports:
     - "8002:80"
    environment:
     APP_KEY: base64:Hsn2BwXdpKHhEiTSDkkuWP1OwbfcZZFQlLoWbjY4lk8=
     APP_FOOTER_TEXT: "LunchRota Demo System"
     APP_DEMO_MODE: "true"
     REDIS_HOST: lunchrota-redis
     DB_HOST: lunchrota-db
     DB_DATABASE: lunchrota
     DB_USERNAME: lunchrota
     DB_PASSWORD: "%33gS#PXXJ$V"
     ASSET_URL: https://lunchrota.andyh.app
  lunchrota-db:
    image: mysql:5.7.30
    restart: unless-stopped
    environment:
     MYSQL_DATABASE: lunchrota
     MYSQL_USER: lunchrota
     MYSQL_PASSWORD: "%33gS#PXXJ$v"
     MYSQL_ROOT_PASSWORD: "%33gS#PXXJ$v"
    volumes:
     - ./lunchrota_db:/var/lib/mysql
  lunchrota-redis:
    image: redis:6.0.4
    restart: unless-stopped
    volumes:
      - ./lunchrota_redis:/data
    entrypoint: redis-server --appendonly yes