/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key",
            "required": true
        },
        {
            "name": "tags",
            "required": false
        }
    ],
    "debugbar.queries.explain": [],
    "filament.exports.download": [
        {
            "name": "export",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.imports.failed-rows.download": [
        {
            "name": "import",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.super-admin.auth.logout": [],
    "filament.super-admin.pages.dashboard": [],
    "filament.super-admin.resources.games.index": [],
    "filament.super-admin.resources.games.create": [],
    "filament.super-admin.resources.games.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.super-admin.resources.users.index": [],
    "filament.super-admin.resources.users.create": [],
    "filament.super-admin.resources.users.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "sanctum.csrf-cookie": [],
    "livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "handle-igdb-webhook": [
        {
            "name": "model",
            "required": true
        },
        {
            "name": "method",
            "required": true
        }
    ],
    "autocomplete": [
        {
            "name": "search",
            "required": true
        }
    ],
    "index": [],
    "dashboard": [],
    "auth.demo-mode": [],
    "login.linked-account.steam": [],
    "login.linked-account.steam.callback": [],
    "search.index": [],
    "games.index": [],
    "games.show": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "keys.create": [],
    "keys.store": [],
    "keys.show": [
        {
            "name": "key",
            "required": true,
            "binding": "id"
        }
    ],
    "keys.claim": [],
    "keys.claimed.index": [],
    "keys.shared.index": [],
    "platforms.show": [
        {
            "name": "platform",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
