// This file will be auto-generated by Spatie TypeScript Transformer
// Run: php artisan typescript:transform

// Placeholder types - will be replaced when transformer runs
export interface PlatformData {
    id: number;
    name: string;
}

export interface UserData {
    id: number;
    name: string;
    email?: string | null;
    image?: string | null;
    bio?: string | null;
    karma?: number | null;
    karma_colour?: string | null;
    admin?: boolean | null;
    approved?: boolean | null;
}

export interface GameData {
    id: number;
    name: string;
    description?: string | null;
    image?: string | null;
    url?: string | null;
    igdb_id?: number | null;
}

export interface DlcData {
    id: number;
    name: string;
    description?: string | null;
    image?: string | null;
    game_id?: number | null;
    game?: GameData | null;
}

export interface KeyData {
    id: number;
    game_id?: number | null;
    dlc_id?: number | null;
    platform_id: number;
    keycode?: string | null;
    message?: string | null;
    created_user_id?: number | null;
    owned_user_id?: number | null;
    name?: string | null;
    image?: string | null;
    url?: string | null;
    platform?: PlatformData | null;
    createdUser?: UserData | null;
    claimedUser?: UserData | null;
    game?: GameData | null;
    dlc?: DlcData | null;
}

export interface GameShowData {
    game: GameData;
    keys: KeyData[];
    dlcCount?: number | null;
    dlcUrl?: string | null;
    igdb?: {
        aggregated_rating?: number;
        aggregated_rating_count?: number;
    } | null;
    genres?: Array<{ id: number; name: string }> | null;
    screenshots?: Array<{ id: number; image_id: string }> | null;
}
